apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - "./infra/k8s/*"
build:
  local:
    push: false
  artifacts:
    - image: ipassternak/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ipassternak/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/pages/**/*.js"
            dest: .
    - image: ipassternak/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ipassternak/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ipassternak/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ipassternak/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
